/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HubNewApp {
        "username": string;
    }
    interface HubNewForm {
    }
}
declare global {
    interface HTMLHubNewAppElement extends Components.HubNewApp, HTMLStencilElement {
    }
    var HTMLHubNewAppElement: {
        prototype: HTMLHubNewAppElement;
        new (): HTMLHubNewAppElement;
    };
    interface HTMLHubNewFormElement extends Components.HubNewForm, HTMLStencilElement {
    }
    var HTMLHubNewFormElement: {
        prototype: HTMLHubNewFormElement;
        new (): HTMLHubNewFormElement;
    };
    interface HTMLElementTagNameMap {
        "hub-new-app": HTMLHubNewAppElement;
        "hub-new-form": HTMLHubNewFormElement;
    }
}
declare namespace LocalJSX {
    interface HubNewApp {
        "username"?: string;
    }
    interface HubNewForm {
    }
    interface IntrinsicElements {
        "hub-new-app": HubNewApp;
        "hub-new-form": HubNewForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hub-new-app": LocalJSX.HubNewApp & JSXBase.HTMLAttributes<HTMLHubNewAppElement>;
            "hub-new-form": LocalJSX.HubNewForm & JSXBase.HTMLAttributes<HTMLHubNewFormElement>;
        }
    }
}
